# -*- coding: utf-8 -*-
"""zadanie git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgAd6c35WaHiiRKY4GZcitEQ3m4-TZPL
"""

def is_criticality_balanced(temperature, neutrons_emitted):
    if temperature < 800 and neutrons_emitted > 500 and (temperature * neutrons_emitted) < 500000:
        return True
    return False


def reactor_efficiency(voltage, current, theoretical_max_power):
    generated_power = voltage * current
    efficiency = (generated_power / theoretical_max_power) * 100

    if efficiency >= 80:
        return "zielony"
    elif 60 <= efficiency < 80:
        return "pomarańczowy"
    elif 30 <= efficiency < 60:
        return "czerwony"
    else:
        return "czarny"


def fail_safe(temperature, neutrons_produced_per_second, threshold):
    product = temperature * neutrons_produced_per_second
    lower_limit = 0.9 * threshold
    upper_limit = 1.1 * threshold

    if product < lower_limit:
        return "LOW"
    elif lower_limit <= product <= upper_limit:
        return "NORMAL"
    else:
        return "DANGER"